apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-search-app
  labels:
    app: image-search
spec:
  replicas: 3
  selector:
    matchLabels:
      app: image-search
  template:
    metadata:
      labels:
        app: image-search
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: image-search
        image: docker-registry/image-search-app:latest
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: image-search-secrets
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: image-search-secrets
type: Opaque
stringData:
  AWS_REGION: "<AWS_REGION>"
  S3_BUCKET: "<BUCKET_NAME>"
  ES_HOST: "<ES_HOST>"
  ES_INDEX: "<ES_INDEX>"
  LEX_BOT_ID: "<BOT_ID>"
  LEX_BOT_ALIAS_ID: "<BOT_ALIAS_ID>"
  AWS_ACCESS_KEY_ID: "<YOUR_ACCESS_KEY>"
  AWS_SECRET_ACCESS_KEY: "<YOUR_SECRET_KEY>"